package com.rockthejvm

object REPS_2024 extends App{

  /*
  Use case 1: The system should be designed to monitor and control the power plant's renewable
  energy sources, including solar panels, wind turbines, and hydropower.
   */

  /*
  Use case 2: The system should be capable of collecting data related to the energy generated by
  renewable sources and storing it in a file.
   */

  /*
  Use case 3: The system should provide a view of the power plant's energy generation and storage
  capacity, allowing operators to adjust the power plant's operation as needed. This
  view should show the data stored in the file.
   */

  /*
  Use case 4: The system should be able to analyse the data collected from renewable sources. It
  should be possible to filter the data on an hourly, daily, weekly and monthly basis. It
  should be possible to sort the data where possible. It must allow a user to search for
  required data stored in the system.
  Data Analysis should include: Mean, Median, Mode, Range, and Midrange

   */

  /*
  Use case 5:  The system should be able to detect and handle issues with renewable energy sources,
  such as low energy output, and equipment malfunction, generating alerts for the
  operators accordingly
   */
}
